function cqPD_genDayFiles(subj)

% addpath(genpath('C:\Users\bugsy\OneDrive\Documents\University\PhD\3rd Year\PD Online Study\cqPD\matlab')) %paths to add, Rhys' oneDrive
% addpath(genpath('E:\projects\toolboxes'))

subjFolderName={'s01','s02','s03','s04','s05','s06','s07','s08','s09','s10',...
    's11','s12','s13','s14','s15','s16','s17','s18','s19','s20','s21','s22','s23',...
    's24','s25','s26','s27','s28','s29','s30','s31','s32','s33','s34','s35','s36',...
    's37','s38','s39','s40','s41','s42','s43','s44','s45','s46','s47','s48','s49',...
    's50','s51','s52','s53','s54','s55','s56','s57','s58','s59','s60'};

% Adjust baseDir to personal use
% baseDir='C:\projects\rhys\prepProd2\data\behavioural'; %Rhys home PC
% baseDir='C:\Users\bugsy\OneDrive\Documents\University\PhD\3rd Year\PD Online Study\cqPD\data'; %Rhys oneDrive
baseDir='C:\Users\yewbreyr\OneDrive\Documents\University\PhD\3rd Year\PD Online Study\cqPD'; %Rhys CHBH PC

subjSaveFolder=fullfile(baseDir,subjFolderName{subj});

if ~isfolder(subjSaveFolder)
    mkdir(subjSaveFolder);
end

cd(subjSaveFolder);

% define the names of all files to be generated
fileNamedays = {'day1', 'day2', 'day3'};


% define header row for each condition file
fileHeader = {'condFiles','startMsg'};

% put together the excel sheet rows required for each sequence condition
day1 = {...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials1.xlsx'],'Welcome! First we will start with  visually guided movement trials. Press space to start';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials2.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials3.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials4.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials5.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials6.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials7.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/A_trials8.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials1.xlsx'],'Now we will continue with some visually guided trials intermixed with trials from memory. Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials2.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials3.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials4.xlsx'],'Press space to start.';...
    };

day2 = {...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials5.xlsx'],'Welcome back! First we will continue with some visually guided trials intermixed with trials from memory. Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials6.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials7.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials8.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials1.xlsx'],'Now we will continue with trials from memory. Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials2.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials3.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials4.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials5.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials6.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials7.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/C_trials8.xlsx'],'Press space to start.';...
    };
    
day3 = {...
    ['orders/conditionsFiles/' subjFolderName{subj} '/B_trials1.xlsx'],'Welcome back! First we will continue with some visually guided trials intermixed with trials from memory. Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Now we  will continue with trials from memory. Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    ['orders/conditionsFiles/' subjFolderName{subj} '/Test_trials.xlsx'],'Press space to start.';...
    };


 trialStruct = [fileHeader; day1];
    
    
    % write to excel file
    xlswrite([fileNamedays{1} '.xlsx'], trialStruct)

 trialStruct = [fileHeader; day2];
    
    
    % write to excel file
    xlswrite([fileNamedays{2} '.xlsx'], trialStruct)
  
trialStruct = [fileHeader; day3];
    
    
    % write to excel file
    xlswrite([fileNamedays{3} '.xlsx'], trialStruct)